name: Run Journey Tests on GitHub
description: Run epr-backend journey tests

inputs:
  epr-backend:
    description: commit hash of epr-backend
  branch:
    description: branch in this repo
    default: main
  journey-test-pr:
    description: is this action being called from a pr in this repo?
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository if not called by Journey Test PR
      if: inputs.journey-test-pr == 'false'
      uses: actions/checkout@v6
      with:
        repository: DEFRA/epr-backend-journey-tests
        ref: ${{inputs.branch}}

    - name: Check for matching epr-backend branch if it is Journey Test PR
      if: inputs.journey-test-pr != 'false'
      id: service-branch
      shell: bash
      run: |
        BRANCH="${{ github.head_ref }}"
        if git ls-remote --heads https://github.com/DEFRA/epr-backend.git "$BRANCH" | grep -q .; then
          echo "ref=$BRANCH" >> "$GITHUB_OUTPUT"
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "ref=main" >> "$GITHUB_OUTPUT"
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Checkout epr-backend repository if it is Journey Test PR and there is a matching service branch
      if: inputs.journey-test-pr != 'false' && steps.service-branch.outputs.exists == 'true'
      uses: actions/checkout@v6
      with:
        repository: DEFRA/epr-backend
        ref: ${{steps.service-branch.outputs.ref}}
        path: epr-backend

    - name: Build Docker image from epr-backend if it is Journey Test PR and same branch exists
      if: inputs.journey-test-pr != 'false' && steps.service-branch.outputs.exists == 'true'
      id: docker-branch
      shell: bash
      run: |
        cd epr-backend
        EPR_BACKEND_SHA=$(git rev-parse --short HEAD)
        IMAGE_TAG="defradigital/epr-backend:${EPR_BACKEND_SHA}"
        docker build -t $IMAGE_TAG .
        echo "image=$EPR_BACKEND_SHA" >> $GITHUB_OUTPUT

    - uses: actions/setup-node@v5
      with:
        node-version-file: .nvmrc
        cache: npm

    - name: Install
      run: npm ci
      shell: bash

    - name: Add hosts entry
      run: |
        sudo echo "127.0.0.1 defra-id-stub" | sudo tee -a /etc/hosts
        # Verify it worked
        cat /etc/hosts
      shell: bash

    - name: Start docker compose with matching Service Branch if it is Journey Test PR
      if: inputs.journey-test-pr != 'false' && steps.service-branch.outputs.exists == 'true'
      shell: bash
      run: |
        EPR_BACKEND=${{ steps.docker-branch.outputs.image }} \
        docker compose up --wait-timeout 300 -d --quiet-pull

    - name: Start docker compose
      if : steps.service-branch.outputs.exists != 'true'
      shell: bash
      run: |
        EPR_BACKEND=${{ inputs.epr-backend }} \
        docker compose up --wait-timeout 300 -d --quiet-pull

    - name: Wait for services to be ready
      shell: bash
      run: |
        echo "Waiting for backend to be ready..."
        timeout 180 bash -c 'until curl -f http://localhost:3001/health; do sleep 5; done'

    - name: Run the tests
      shell: bash
      run: |
        npm run test:tagged "not @smoketest"
        npm run report

    - name: debug
      if: always()
      run: |
        docker compose logs > logs.txt
        docker ps
      shell: bash

    - name: Upload allure report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: ./allure-report

    - name: Upload docker compose logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: docker-compose-logs
        path: ./logs.txt

    - name: Fail this step if FAILED file exists
      if: always()
      run: |
        if [ -f "FAILED" ]; then
          exit 1
        fi
      shell: bash
