name: Run Journey Tests on GitHub
description: Run epr-backend journey tests

inputs:
  epr-backend:
    description: commit hash of epr-backend
  branch:
    description: branch in this repo
    default: main
  journey-test-pr:
    description: is this action being called from a pr in this repo?
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository if not called by Journey Test PR
      if: inputs.journey-test-pr == 'false'
      uses: actions/checkout@v5
      with:
        repository: DEFRA/epr-backend-journey-tests
        ref: ${{inputs.branch}}

    - uses: actions/setup-node@v5
      with:
        node-version-file: .nvmrc
        cache: npm

    - name: Install
      run: npm ci
      shell: bash

    - name: Add hosts entry
      run: |
        sudo echo "127.0.0.1 defra-id-stub" | sudo tee -a /etc/hosts
        # Verify it worked
        cat /etc/hosts
      shell: bash

    - name: Start docker compose
      shell: bash
      run: |
        EPR_BACKEND=${{ inputs.epr-backend }} \
        docker compose up --wait-timeout 300 -d --quiet-pull

    - name: Wait for services to be ready
      shell: bash
      run: |
        echo "Waiting for backend to be ready..."
        timeout 180 bash -c 'until curl -f http://localhost:3001/health; do sleep 5; done'

    - name: Run the tests
      shell: bash
      run: |
        npm run test:tagged "not @smoketest"

    - name: debug
      if: always()
      run: |
        docker compose logs > logs.txt
        docker ps
      shell: bash

    - name: Upload allure report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: ./allure-report

    - name: Upload docker compose logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: docker-compose-logs
        path: ./logs.txt

    - name: Fail this step if FAILED file exists
      if: always()
      run: |
        if [ -f "FAILED" ]; then
          exit 1
        fi
      shell: bash
