name: Run Journey Tests on GitHub

inputs:
  epr-backend:
    required: false
    type: string
  branch:
    required: false
    type: string
    default: main

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        repository: DEFRA/epr-backend-journey-tests

    - name: Docker Login
      uses: DEFRA/cdp-build-action/docker-login@main

    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: npm
    - name: Setup the tests
      run: npm i
      shell: bash

    - name: Start docker compose
      shell: bash
      run: |
        EPR_BACKEND=${{inputs.epr-backend}} \
        docker compose up --wait-timeout 300 -d --quiet-pull
    - name: Run the tests
      shell: bash
      run: |
        npm run test
    - name: debug
      if: always()
      run: |
        docker compose logs > logs.txt
        docker ps
      shell: bash
    - name: Upload allure report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: ./allure-report
    - name: Upload docker compose logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: docker-compose-logs
        path: ./logs.txt
